FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# คัดลอกโค้ด
COPY escpos_splitter.py /app/

EXPOSE 9100

CMD ["python", "-u", "escpos_splitter.py"]
